/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.MetodosDeDB;
import Clases.Productos;
import javax.swing.ImageIcon;


/**
 *
 * @author Jhoan
 */
public class Consultar extends javax.swing.JFrame {

    MetodosDeDB MetodosDB = new MetodosDeDB();
    int y, x;
    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.TextoApagado(false);
         setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());
        
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        TituloAgregar = new javax.swing.JLabel();
        txtCosto = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JLabel();
        txtCod = new javax.swing.JLabel();
        txtSeHanVendido = new javax.swing.JLabel();
        errornoexiste = new javax.swing.JLabel();
        Enviar = new javax.swing.JLabel();
        txtCanti1 = new javax.swing.JLabel();
        txtSeHanVendido1 = new javax.swing.JLabel();
        txtCanti2 = new javax.swing.JLabel();
        txtCosto1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtCod1 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JLabel();
        txtUbicacion2 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/consulta (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 100));

        txtConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 290, 50));

        TituloAgregar.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        TituloAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/TituloConsultarProd.png"))); // NOI18N
        TituloAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloAgregarMouseExited(evt);
            }
        });
        jPanel1.add(TituloAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 400, 60));

        txtCosto.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtCosto.setText("Costo");
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 330, 30));

        txtNombre.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtNombre.setText("Nombre");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 330, 30));

        txtPrecio.setFont(new java.awt.Font("Book Antiqua", 0, 48)); // NOI18N
        txtPrecio.setText("Precio");
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 140, -1));

        txtCod.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtCod.setText("Codigo");
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 330, 30));

        txtSeHanVendido.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtSeHanVendido.setText("Se han vendido");
        jPanel1.add(txtSeHanVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 330, 30));

        errornoexiste.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        errornoexiste.setForeground(new java.awt.Color(255, 51, 0));
        errornoexiste.setText("El producto no existe");
        jPanel1.add(errornoexiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/buscar.png"))); // NOI18N
        Enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnviarMouseExited(evt);
            }
        });
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 50, 50));

        txtCanti1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtCanti1.setText("Cantidad");
        jPanel1.add(txtCanti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 330, 30));

        txtSeHanVendido1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtSeHanVendido1.setForeground(new java.awt.Color(255, 51, 102));
        txtSeHanVendido1.setText("Se han vendido");
        jPanel1.add(txtSeHanVendido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, 30));

        txtCanti2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtCanti2.setForeground(new java.awt.Color(255, 51, 102));
        txtCanti2.setText("Cantidad");
        jPanel1.add(txtCanti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 130, 30));

        txtCosto1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtCosto1.setForeground(new java.awt.Color(255, 51, 102));
        txtCosto1.setText("Costo");
        jPanel1.add(txtCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 130, 30));

        txtNombre1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(255, 51, 102));
        txtNombre1.setText("Nombre");
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 130, 30));

        txtCod1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtCod1.setForeground(new java.awt.Color(255, 51, 102));
        txtCod1.setText("Codigo");
        jPanel1.add(txtCod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, 30));

        txtPrecio1.setFont(new java.awt.Font("Book Antiqua", 0, 48)); // NOI18N
        txtPrecio1.setForeground(new java.awt.Color(255, 51, 102));
        txtPrecio1.setText("Precio");
        jPanel1.add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 140, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, 20));

        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseExited(evt);
            }
        });
        jPanel1.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        txtUbicacion2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtUbicacion2.setText("Ubicacion");
        jPanel1.add(txtUbicacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 330, 30));

        txtUbicacion.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        txtUbicacion.setForeground(new java.awt.Color(255, 51, 102));
        txtUbicacion.setText("Ubicacion");
        jPanel1.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMouseEntered
       Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/buscar (1).png")));
    }//GEN-LAST:event_EnviarMouseEntered

    private void EnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMouseExited
        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/buscar.png")));
    }//GEN-LAST:event_EnviarMouseExited

    private void TituloAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloAgregarMouseEntered
         TituloAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/TituloConsultarProdMorado.png")));
    }//GEN-LAST:event_TituloAgregarMouseEntered

    private void TituloAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloAgregarMouseExited
        TituloAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/TituloConsultarProd.png")));
    }//GEN-LAST:event_TituloAgregarMouseExited

    private void EnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMouseClicked
       
       
        try {
            Productos Respuesta =this.MetodosDB.consultartodoporResultSet( this.txtConsultar.getText());
            this.txtCanti1.setText(Respuesta.getCantidad());
            this.txtCod.setText(Respuesta.getCodigo());
            this.txtCosto.setText( Respuesta.getPrecioDeCompra());
            this.txtNombre.setText( Respuesta.getNombre());
            this.txtPrecio.setText(  Respuesta.getPrecioDeVenta());
            this.txtSeHanVendido.setText(  Respuesta.getVentasDesde());
            this.txtUbicacion2.setText(  Respuesta.getUbicacion());
            
            this.TextoApagado(true);
            this.errornoexiste.setVisible(false);
        } catch (Exception e) {
            System.out.println("Error en enviar consultar "+e);
            this.errornoexiste.setVisible(true);
            this.TextoApagado(false);
            this.errornoexiste.setVisible(true);
        }
       
    }//GEN-LAST:event_EnviarMouseClicked

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        this.regresar();
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void RegresarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseEntered
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_RegresarbtnMouseEntered

    private void RegresarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseExited
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_RegresarbtnMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
       x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked
public void TextoApagado(boolean si){
    if(si==true){
         this.txtSeHanVendido.setVisible(true);
        this.txtCod.setVisible(true);
        this.txtCosto.setVisible(true);
        this.txtNombre.setVisible(true);
        this.txtPrecio.setVisible(true);
        this.txtCanti1.setVisible(true);
        this.txtSeHanVendido1.setVisible(true);
        this.txtCod1.setVisible(true);
        this.txtCosto1.setVisible(true);
        this.txtNombre1.setVisible(true);
        this.txtPrecio1.setVisible(true);
        this.txtCanti2.setVisible(true);
        this.txtUbicacion2.setVisible(true);
        this.txtUbicacion.setVisible(true);
        
    }else{
        this.txtSeHanVendido.setVisible(false);
        this.txtCod.setVisible(false);
        this.txtCosto.setVisible(false);
        this.txtNombre.setVisible(false);
        this.txtPrecio.setVisible(false);
        this.txtCanti1.setVisible(false);
        this.errornoexiste.setVisible(false);
         this.txtSeHanVendido1.setVisible(false);
        this.txtCod1.setVisible(false);
        this.txtCosto1.setVisible(false);
        this.txtNombre1.setVisible(false);
        this.txtPrecio1.setVisible(false);
        this.txtCanti2.setVisible(false);
        this.txtUbicacion2.setVisible(false);
        this.txtUbicacion.setVisible(false);
        
        
    }
}
public void regresar(){
       ProductosI principal = new ProductosI();
            principal.setVisible(true);
            this.dispose();
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enviar;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel Regresarbtn;
    private javax.swing.JLabel TituloAgregar;
    private javax.swing.JLabel errornoexiste;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCanti1;
    private javax.swing.JLabel txtCanti2;
    private javax.swing.JLabel txtCod;
    private javax.swing.JLabel txtCod1;
    private javax.swing.JTextField txtConsultar;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtCosto1;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtPrecio;
    private javax.swing.JLabel txtPrecio1;
    private javax.swing.JLabel txtSeHanVendido;
    private javax.swing.JLabel txtSeHanVendido1;
    private javax.swing.JLabel txtUbicacion;
    private javax.swing.JLabel txtUbicacion2;
    // End of variables declaration//GEN-END:variables
}
