/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


import Clases.MetodosDeDB;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhoan
 */
public class Editar extends javax.swing.JFrame {

 MetodosDeDB MetodosDB = new MetodosDeDB();

    int y, x;

    /**
     * Creates new form Consultar
     */
    public Editar() {
        initComponents();
        this.Errordatosincorrectos.setVisible(false);
        this.setLocationRelativeTo(null);
        this.agregaritemschoise();
         setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVender = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Errordatosincorrectos = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jLabel2 = new javax.swing.JLabel();
        txtEdit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(250, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVender.setBackground(new java.awt.Color(255, 255, 255));
        PanelVender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        PanelVender.setPreferredSize(new java.awt.Dimension(250, 350));
        PanelVender.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelVenderMouseDragged(evt);
            }
        });
        PanelVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelVenderMousePressed(evt);
            }
        });
        PanelVender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Editarprod.png"))); // NOI18N
        Titulo.setText("Agregar Producto");
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });
        PanelVender.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 50));

        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVender.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Ingrese el nombre");
        PanelVender.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Ingrese el Valor a editar");
        PanelVender.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, -1));

        Errordatosincorrectos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Errordatosincorrectos.setForeground(new java.awt.Color(255, 51, 51));
        Errordatosincorrectos.setText("Datos incorrectos ");
        PanelVender.add(Errordatosincorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/lapiz.png"))); // NOI18N
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        PanelVender.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 50, 50));

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/senal (1).png"))); // NOI18N
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarMouseExited(evt);
            }
        });
        PanelVender.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Cancelar");
        PanelVender.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Editar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        PanelVender.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelVender.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 20, 20));

        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseExited(evt);
            }
        });
        PanelVender.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        choice1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        choice1.setName(""); // NOI18N
        choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice1MouseClicked(evt);
            }
        });
        PanelVender.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("¿Qué desea editar?");
        PanelVender.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, -1));

        txtEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVender.add(txtEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 170, -1));

        getContentPane().add(PanelVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        
        String Nombre,Seleccion;
        Nombre = this.txtNombre.getText();
        Seleccion = this.seleccionar(this.choice1.getItem(this.choice1.getSelectedIndex()));
        
        try {

            if (Nombre.isEmpty() == false && Seleccion != "0") {

                this.MetodosDB.EditarPor(Integer.parseInt(Seleccion), this.txtEdit.getText(), 2,this.txtNombre.getText() );
//            System.out.println("INSERT INTO Productos (prod_id,prod_descripcion,prod_costo,prod_venta,prod_cantidad,"
//                    + "ventas_desde,prod_fechavencimiento)values"
//                    + "(null" + "," + "'" + Nombre + "'" + "," + "'" + Costo + "'" + "," + "'"
//                    + Venta + "'" + "," + "'" + Cantidad + "'" + ",0,'" +FechaCaducidad.toString()+ "');");

                this.PonerEnBlancoTxt();
                this.Errordatosincorrectos.setVisible(false);

            } else {
                this.Errordatosincorrectos.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("Error en insertar2 " + e);
            this.Errordatosincorrectos.setVisible(true);
        }

    }//GEN-LAST:event_EditarMouseClicked

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/Lapiz(2).png"))); // NOI18N

    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/lapiz.png"))); // NOI18N
        
    }//GEN-LAST:event_EditarMouseExited

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        this.regresar();
    }//GEN-LAST:event_CancelarMouseClicked

    private void CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseEntered
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/senal.png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseEntered

    private void CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseExited
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/senal (1).png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void PanelVenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_PanelVenderMousePressed

    private void PanelVenderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_PanelVenderMouseDragged

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Editarprodverde.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Editarprod.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseExited

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        this.regresar();
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void RegresarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseEntered
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_RegresarbtnMouseEntered

    private void RegresarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseExited
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_RegresarbtnMouseExited

    private void choice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseClicked
        
    }//GEN-LAST:event_choice1MouseClicked
    public void regresar() {
        ProductosI principal = new ProductosI();
        principal.setVisible(true);
        this.dispose();
    }
    public String seleccionar(String Seleccion){
        switch(Seleccion){
            case "":
                Seleccion = "0";
                break;
                case "Nombre":
                Seleccion = "2";
                break;
                case "Costo":
                Seleccion = "3";
                break;
                case "Venta":
                Seleccion = "4";
                break;
                case "Cantidad":
                Seleccion = "5";
                break;
                case "Fecha de Vencimiento":
                Seleccion = "6";
                break;
                case "Ubicacion":
                Seleccion = "7";
                break;
        }
        return Seleccion;
    }

    public void PonerEnBlancoTxt() {
        
        this.txtNombre.setText("");
        this.txtEdit.setText("");
        this.choice1.select(0);
       
    }
    public void agregaritemschoise(){
        this.choice1.addItem("");
        this.choice1.select(0);
        this.choice1.addItem("Nombre");
        this.choice1.addItem("Costo");
        this.choice1.addItem("Venta");
        this.choice1.addItem("Cantidad");
        this.choice1.addItem("Fecha de vencimiento");
        this.choice1.addItem("Ubicacion");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Errordatosincorrectos;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPanel PanelVender;
    private javax.swing.JLabel Regresarbtn;
    private javax.swing.JLabel Titulo;
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEdit;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
