/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.ConexionDB;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhoan
 */
public class Insertar extends javax.swing.JFrame {

    ConexionDB db = new ConexionDB();

    int y, x;

    /**
     * Creates new form Consultar
     */
    public Insertar() {
        initComponents();
        this.Errordatosincorrectos.setVisible(false);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVender = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Errordatosincorrectos = new javax.swing.JLabel();
        Agregar = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        Minimizar = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(250, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVender.setBackground(new java.awt.Color(255, 255, 255));
        PanelVender.setPreferredSize(new java.awt.Dimension(250, 350));
        PanelVender.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelVenderMouseDragged(evt);
            }
        });
        PanelVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelVenderMousePressed(evt);
            }
        });
        PanelVender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/titulopanelagregar.png"))); // NOI18N
        Titulo.setText("Agregar Producto");
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });
        PanelVender.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 50));

        PanelVender.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 170, -1));

        PanelVender.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, -1));

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        PanelVender.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, -1));

        PanelVender.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Ingrese el nombre");
        PanelVender.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Ingrese el costo");
        PanelVender.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Ingrese la cantidad");
        PanelVender.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Ingrese el valor de venta");
        PanelVender.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        Errordatosincorrectos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Errordatosincorrectos.setForeground(new java.awt.Color(255, 51, 51));
        Errordatosincorrectos.setText("Datos incorrectos ");
        PanelVender.add(Errordatosincorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/agregar-archivo (2).png"))); // NOI18N
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarMouseExited(evt);
            }
        });
        PanelVender.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 50, 50));

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/archivo (1).png"))); // NOI18N
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarMouseExited(evt);
            }
        });
        PanelVender.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Cancelar");
        PanelVender.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Agregar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        PanelVender.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Ingrese la ubicación");
        PanelVender.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txtFecha.setForeground(new java.awt.Color(153, 153, 153));
        txtFecha.setText("AA/MM/DD");
        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaFocusGained(evt);
            }
        });
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMouseClicked(evt);
            }
        });
        PanelVender.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelVender.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 20, 20));

        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseExited(evt);
            }
        });
        PanelVender.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Ingrese la fecha de caducidad");
        PanelVender.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        PanelVender.add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 170, -1));

        getContentPane().add(PanelVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        this.db.conexion();
        String Nombre, Costo, Venta, Cantidad, FechaCaducidad, Ubicacion;
        Nombre = this.txtNombre.getText();
        Costo = this.txtCosto.getText();
        Venta = this.txtValor.getText();
        Cantidad = this.txtCantidad.getText();
        FechaCaducidad = this.txtFecha.getText();
        Ubicacion = this.txtUbicacion.getText();
        try {

            if (Costo.isEmpty() == false
                    && Venta.isEmpty() == false
                    && Cantidad.isEmpty() == false
                    && Nombre.isEmpty() == false) {

                this.db.insertar("INSERT INTO Productos (prod_id,prod_descripcion,prod_costo,prod_venta,prod_cantidad,"
                        + "ventas_desde,prod_fechavencimiento,prod_ubicacion)values"
                        + "(null" + "," + "'" + Nombre + "'" + "," + "'" + Costo + "'" + "," + "'"
                        + Venta + "'" + "," + "'" + Cantidad + "'" + ",0,'" + FechaCaducidad + "','" + Ubicacion + "'" + ");");
//            System.out.println("INSERT INTO Productos (prod_id,prod_descripcion,prod_costo,prod_venta,prod_cantidad,"
//                    + "ventas_desde,prod_fechavencimiento)values"
//                    + "(null" + "," + "'" + Nombre + "'" + "," + "'" + Costo + "'" + "," + "'"
//                    + Venta + "'" + "," + "'" + Cantidad + "'" + ",0,'" +FechaCaducidad.toString()+ "');");

                this.PonerEnBlancoTxt();
                this.Errordatosincorrectos.setVisible(false);

            } else {
                this.Errordatosincorrectos.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("Error en insertar2 " + e);
            this.Errordatosincorrectos.setVisible(true);
        }
    }//GEN-LAST:event_AgregarMouseClicked

    private void AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseEntered
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/agregar-archivo (1).png"))); // NOI18N

    }//GEN-LAST:event_AgregarMouseEntered

    private void AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseExited
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/agregar-archivo (2).png"))); // NOI18N

    }//GEN-LAST:event_AgregarMouseExited

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        this.regresar();
    }//GEN-LAST:event_CancelarMouseClicked

    private void CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseEntered
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/archivo.png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseEntered

    private void CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseExited
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/archivo (1).png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void PanelVenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_PanelVenderMousePressed

    private void PanelVenderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_PanelVenderMouseDragged

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/titulopanelagregarazul.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/titulopanelagregar.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseExited

    private void txtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMouseClicked
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        this.txtFecha.setText("");
    }//GEN-LAST:event_txtFechaMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        this.regresar();
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void RegresarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseEntered
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_RegresarbtnMouseEntered

    private void RegresarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseExited
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_RegresarbtnMouseExited

    private void txtFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusGained
        if (this.txtFecha.getText().equals("AA/MM/DD")) {
            this.txtFecha.setText("");
        }
        if (this.txtFecha.getText().isEmpty() == true) {
            this.txtFecha.setText("");
        }

    }//GEN-LAST:event_txtFechaFocusGained
    public void regresar() {
        ProductosI principal = new ProductosI();
        principal.setVisible(true);
        this.dispose();
    }

    public void PonerEnBlancoTxt() {
        this.txtCantidad.setText("");
        this.txtValor.setText("");
        this.txtNombre.setText("");
        this.txtCosto.setText("");
        this.txtFecha.setText("");
        this.txtUbicacion.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Errordatosincorrectos;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPanel PanelVender;
    private javax.swing.JLabel Regresarbtn;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
