/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.MetodosDeDB;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhoan
 */
public class Principal extends javax.swing.JFrame {

    int y, x;
    MetodosDeDB MD = new MetodosDeDB();
    String DineroVar;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pandinero.setVisible(false);
        try {
            this.DineroVar = this.MD.Dinero();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        NubiaLetrero = new javax.swing.JLabel();
        LbVender = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        moneda = new javax.swing.JLabel();
        pandinero = new javax.swing.JPanel();
        dineroactual = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbProductos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, 20));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 20, 20));

        NubiaLetrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nubia.png"))); // NOI18N
        NubiaLetrero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NubiaLetreroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NubiaLetreroMouseExited(evt);
            }
        });
        jPanel1.add(NubiaLetrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        LbVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/hucha (1).png"))); // NOI18N
        LbVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbVenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbVenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbVenderMouseExited(evt);
            }
        });
        jPanel1.add(LbVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, 140));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vender");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 110, 20));

        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/pregunta2.png"))); // NOI18N
        Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreditosMouseExited(evt);
            }
        });
        jPanel1.add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 50, 50));

        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/moneda1.png"))); // NOI18N
        moneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monedaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monedaMouseExited(evt);
            }
        });
        jPanel1.add(moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 50, 50));

        pandinero.setBackground(new java.awt.Color(255, 255, 255));
        pandinero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pandinero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dineroactual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dineroactual.setText("0");
        pandinero.add(dineroactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 40, 106, 28));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dinero");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pandinero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jPanel1.add(pandinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 80));

        LbProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/productos-lacteos.png"))); // NOI18N
        LbProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbProductosMouseExited(evt);
            }
        });
        jPanel1.add(LbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 140, 140));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Productos");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit.png")));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void LbVenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbVenderMouseEntered
        LbVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/hucha.png")));
    }//GEN-LAST:event_LbVenderMouseEntered

    private void LbVenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbVenderMouseExited
        LbVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/hucha (1).png")));
    }//GEN-LAST:event_LbVenderMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void LbVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbVenderMouseClicked
        Vender vend = new Vender();
        vend.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbVenderMouseClicked

    private void NubiaLetreroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NubiaLetreroMouseEntered
        NubiaLetrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nubia2.png")));
    }//GEN-LAST:event_NubiaLetreroMouseEntered

    private void NubiaLetreroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NubiaLetreroMouseExited
        NubiaLetrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nubia.png")));
    }//GEN-LAST:event_NubiaLetreroMouseExited

    private void CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseClicked
        this.Navegarpagna("https://github.com/JhoanVanDam/");
    }//GEN-LAST:event_CreditosMouseClicked

    private void CreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseEntered
        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/pregunta.png"))); // NOI18N

    }//GEN-LAST:event_CreditosMouseEntered

    private void CreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseExited
        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/pregunta2.png"))); // NOI18N
        
    }//GEN-LAST:event_CreditosMouseExited

    private void monedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaMouseExited
        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/moneda1.png")));
        this.pandinero.setVisible(false);
    }//GEN-LAST:event_monedaMouseExited

    private void monedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaMouseEntered
        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/moneda.png")));
        
        
            
            this.dineroactual.setText(DineroVar);
       
        this.pandinero.setVisible(true);
    }//GEN-LAST:event_monedaMouseEntered

    private void LbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProductosMouseClicked
        ProductosI prod = new ProductosI();
        prod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbProductosMouseClicked

    private void LbProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProductosMouseEntered
            LbProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/productos-lacteos (1).png")));
    
    }//GEN-LAST:event_LbProductosMouseEntered

    private void LbProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProductosMouseExited
       LbProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/productos-lacteos.png")));
    
    }//GEN-LAST:event_LbProductosMouseExited
    public void Navegarpagna(String url) {
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            try {
                java.net.URI uri = new java.net.URI(url);
                desktop.browse(uri);
            } catch (URISyntaxException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Creditos;
    private javax.swing.JLabel LbProductos;
    private javax.swing.JLabel LbVender;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel NubiaLetrero;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel dineroactual;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moneda;
    private javax.swing.JPanel pandinero;
    // End of variables declaration//GEN-END:variables
}
