/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


import java.io.IOException;
import java.net.URISyntaxException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhoan
 */
public class ProductosI extends javax.swing.JFrame {

    int y, x;
   
    
    /**
     * Creates new form Principal
     */
    public ProductosI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbAñadir = new javax.swing.JLabel();
        LbIcono = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        NubiaLetrero = new javax.swing.JLabel();
        LbConsultar = new javax.swing.JLabel();
        LbDelete = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/anadir (3).png"))); // NOI18N
        LbAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbAñadirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbAñadirMouseExited(evt);
            }
        });
        jPanel1.add(LbAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 100));

        LbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/medicine.png"))); // NOI18N
        LbIcono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbIconoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbIconoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbIconoMouseExited(evt);
            }
        });
        jPanel1.add(LbIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 100));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png"))); // NOI18N
        Salir.setText("jLabel2");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, 20));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 20, 20));

        NubiaLetrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nubia.png"))); // NOI18N
        NubiaLetrero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NubiaLetreroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NubiaLetreroMouseExited(evt);
            }
        });
        jPanel1.add(NubiaLetrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        LbConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/consulta.png"))); // NOI18N
        LbConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbConsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbConsultarMouseExited(evt);
            }
        });
        jPanel1.add(LbConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 100, 100));

        LbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/bote.png"))); // NOI18N
        LbDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LbDeleteMouseExited(evt);
            }
        });
        jPanel1.add(LbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/todoslosprod.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 20));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Editar");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 110, 20));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 110, 20));

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/editar (1).png"))); // NOI18N
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        jPanel1.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 100, 100));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agregar");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, 20));

        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/pregunta2.png"))); // NOI18N
        Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreditosMouseExited(evt);
            }
        });
        jPanel1.add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 50, 50));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Buscar");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 110, 20));

        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseExited(evt);
            }
        });
        jPanel1.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit.png")));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/InterfazClave/Exit2.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void LbAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAñadirMouseClicked
        Insertar cons = new Insertar();
        cons.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbAñadirMouseClicked

    private void LbAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAñadirMouseEntered
        LbAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/mas.png")));
    }//GEN-LAST:event_LbAñadirMouseEntered

    private void LbAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAñadirMouseExited
        LbAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/anadir (3).png")));
    }//GEN-LAST:event_LbAñadirMouseExited

    private void LbConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbConsultarMouseEntered
        LbConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/consulta (1).png")));
    }//GEN-LAST:event_LbConsultarMouseEntered

    private void LbConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbConsultarMouseExited
        LbConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/consulta.png")));
    }//GEN-LAST:event_LbConsultarMouseExited

    private void LbDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbDeleteMouseEntered
        LbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/bote2.png")));
    }//GEN-LAST:event_LbDeleteMouseEntered

    private void LbDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbDeleteMouseExited
        LbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/bote.png")));
    }//GEN-LAST:event_LbDeleteMouseExited

    private void LbIconoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbIconoMouseEntered
        LbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/injection.png")));
    }//GEN-LAST:event_LbIconoMouseEntered

    private void LbIconoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbIconoMouseExited
        LbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/medicine.png")));
    }//GEN-LAST:event_LbIconoMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void LbDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbDeleteMouseClicked
        Eliminar Del = new Eliminar();
        Del.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LbDeleteMouseClicked

    private void LbConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbConsultarMouseClicked
        Consultar Consu = new Consultar();
        Consu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbConsultarMouseClicked

    private void NubiaLetreroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NubiaLetreroMouseEntered
        NubiaLetrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nubia2.png")));
    }//GEN-LAST:event_NubiaLetreroMouseEntered

    private void NubiaLetreroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NubiaLetreroMouseExited
        NubiaLetrero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Nubia.png")));
    }//GEN-LAST:event_NubiaLetreroMouseExited

    private void LbIconoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbIconoMouseClicked
        VistaDeProducto todos = new VistaDeProducto();
        todos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LbIconoMouseClicked

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/editar.png"))); // NOI18N

    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/editar (1).png"))); // NOI18N

    }//GEN-LAST:event_EditarMouseExited

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        Editar edit = new Editar();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditarMouseClicked

    private void CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseClicked
        this.Navegarpagna("https://github.com/JhoanVanDam/");
    }//GEN-LAST:event_CreditosMouseClicked

    private void CreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseEntered
        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/pregunta.png"))); // NOI18N

    }//GEN-LAST:event_CreditosMouseEntered

    private void CreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseExited
        Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/pregunta2.png"))); // NOI18N
        
    }//GEN-LAST:event_CreditosMouseExited

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        this.regresar();
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void RegresarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseEntered
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_RegresarbtnMouseEntered

    private void RegresarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseExited
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_RegresarbtnMouseExited
    public void Navegarpagna(String url) {
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            try {
                java.net.URI uri = new java.net.URI(url);
                desktop.browse(uri);
            } catch (URISyntaxException ex) {
                Logger.getLogger(ProductosI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ProductosI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
     public void regresar() {
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Creditos;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel LbAñadir;
    private javax.swing.JLabel LbConsultar;
    private javax.swing.JLabel LbDelete;
    private javax.swing.JLabel LbIcono;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JLabel NubiaLetrero;
    private javax.swing.JLabel Regresarbtn;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
