/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.FacturaClase;
import Clases.MetodosDeDB;
import Clases.Productos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhoan
 */
public class Vender extends javax.swing.JFrame {

    ArrayList<Productos> Prod;
    MetodosDeDB MetodosDB = new MetodosDeDB();
    int y, x;

    /**
     * Creates new form Factura
     */
    public Vender() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Errordatosincorrectos.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());
        Prod = new ArrayList<>();
        this.lablista.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVender = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Errordatosincorrectos = new javax.swing.JLabel();
        Vender = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lablista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelVender.setBackground(new java.awt.Color(255, 255, 255));
        PanelVender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        PanelVender.setPreferredSize(new java.awt.Dimension(250, 350));
        PanelVender.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelVenderMouseDragged(evt);
            }
        });
        PanelVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelVenderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelVenderMousePressed(evt);
            }
        });
        PanelVender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/venderproducto.png"))); // NOI18N
        Titulo.setText("Agregar Producto");
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });
        PanelVender.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 50));

        txtNombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVender.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Ingrese el nombre");
        PanelVender.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        Errordatosincorrectos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Errordatosincorrectos.setForeground(new java.awt.Color(255, 51, 51));
        Errordatosincorrectos.setText("Datos incorrectos ");
        PanelVender.add(Errordatosincorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/comercio.png"))); // NOI18N
        Vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VenderMouseExited(evt);
            }
        });
        PanelVender.add(Vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 50, 50));

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/disgusto.png"))); // NOI18N
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarMouseExited(evt);
            }
        });
        PanelVender.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Cancelar");
        PanelVender.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Agregar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        PanelVender.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVender.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setText("Ingrese la cantidad");
        PanelVender.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelVender.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 20, 20));

        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseExited(evt);
            }
        });
        PanelVender.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Vender");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        PanelVender.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/agregarbtn.png"))); // NOI18N
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnagregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnagregarMouseExited(evt);
            }
        });
        PanelVender.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 50, 50));

        lablista.setEditable(false);
        lablista.setColumns(20);
        lablista.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lablista.setRows(5);
        lablista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 204), 1, true));
        jScrollPane1.setViewportView(lablista);

        PanelVender.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVender, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVender, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseClicked

       
        String Vendidos;
        int cantidad;
        

        if (this.Prod.isEmpty() == false) {

            try {
                int Valor = 0;
                short Cantidad = 0;
                String Descripcion = "";

                for (int k = 0; k < this.Prod.size(); k++) {
                    Valor = Valor + (Integer.parseInt(this.Prod.get(k).getPrecioDeVenta()) * Integer.parseInt(this.Prod.get(k).getCantidad()));
                    Cantidad = (short) (Cantidad + Double.parseDouble(this.Prod.get(k).getCantidad()));
                    Descripcion = Descripcion +"\n"+ "Nombre:"+this.Prod.get(k).getNombre() 
                            +"\n"+"Cantidad:"+this.Prod.get(k).getCantidad() +"\n";

                    Vendidos = (short) (Integer.parseInt(this.MetodosDB.consultarpor(6, 2, Prod.get(k).getNombre())) + Integer.parseInt(this.Prod.get(k).getCantidad())) + "";
                    this.MetodosDB.EditarPor(7, Vendidos, 2, this.Prod.get(k).getNombre());

                    cantidad = Integer.parseInt(this.MetodosDB.consultarpor(5, 2, this.Prod.get(k).getNombre())) - Integer.parseInt(this.Prod.get(k).getCantidad());
                    System.out.println(cantidad);
                    this.MetodosDB.EditarPor(5, cantidad + "", 2, this.Prod.get(k).getNombre());
                }
                
                this.PonerEnBlancoTxt();
                this.Errordatosincorrectos.setVisible(false);
                this.DineroRecolectar();
                
                Factura fact = new Factura(new FacturaClase(Valor + "", Cantidad + "", Descripcion + "",this.Prod));
                fact.setVisible(true);
                this.dispose();

            } catch (Exception e) {
                System.out.println("Error en insertar2 " + e);
                this.Errordatosincorrectos.setVisible(true);
            }
        } else {
            this.Errordatosincorrectos.setVisible(true);
        }
    }//GEN-LAST:event_VenderMouseClicked

    private void VenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseEntered
        Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/comercio-de-personas.png"))); // NOI18N

    }//GEN-LAST:event_VenderMouseEntered

    private void VenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseExited
        Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/comercio.png"))); // NOI18N

    }//GEN-LAST:event_VenderMouseExited

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        this.regresar();
    }//GEN-LAST:event_CancelarMouseClicked

    private void CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseEntered
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/disgusto (1).png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseEntered

    private void CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseExited
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/disgusto.png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void PanelVenderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_PanelVenderMouseDragged

    private void PanelVenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_PanelVenderMousePressed

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/venderproductoazul.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/venderproducto.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseExited

    private void PanelVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelVenderMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        this.regresar();
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void RegresarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseEntered
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_RegresarbtnMouseEntered

    private void RegresarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseExited
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_RegresarbtnMouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    private void btnagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseClicked

        try {

            if (this.txtNombre.getText().isEmpty() == false
                    && this.MetodosDB.ExisteoNO(txtNombre.getText()) == true
                    && Integer.parseInt(this.txtCantidad.getText()) <= Integer.parseInt(this.MetodosDB.ConsultarVender(this.txtNombre.getText()))
                    && Integer.parseInt(this.MetodosDB.ConsultarVender(txtNombre.getText())) > 0) {

                Productos prod = this.MetodosDB.consultartodoporResultSetVender( this.txtNombre.getText());
                prod.setCantidad(this.txtCantidad.getText());
                this.Prod.add(prod);
                this.lablista.setText(this.lablista.getText() + prod.getNombre() + ",");
                this.PonerEnBlancoTxt();

            } else {
                this.Errordatosincorrectos.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("Error en insertar2 " + e);
            this.Errordatosincorrectos.setVisible(true);
        }


    }//GEN-LAST:event_btnagregarMouseClicked

    private void btnagregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseEntered
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/agregar.png"))); // NOI18N

    }//GEN-LAST:event_btnagregarMouseEntered

    private void btnagregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseExited
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/agregarbtn.png"))); // NOI18N

    }//GEN-LAST:event_btnagregarMouseExited
    public void regresar() {
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }

    public void PonerEnBlancoTxt() {

        this.txtNombre.setText("");
        this.txtCantidad.setText("");

    }
    public Double DineroRecolectar() throws SQLException{
        double din=0;
        for(int k=0;k<this.Prod.size();k++){
            din = din + (Double.parseDouble(this.Prod.get(k).getPrecioDeVenta())
                    * Double.parseDouble(this.Prod.get(k).getCantidad()));
        }
        this.MetodosDB.editarDinero(din);
        System.out.println("EL DINERO ES"+din);
        return din;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Errordatosincorrectos;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPanel PanelVender;
    private javax.swing.JLabel Regresarbtn;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Vender;
    private javax.swing.JLabel btnagregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lablista;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
